name: restapi unit test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ feature/* ]
  schedule:
    - cron: "0 0 * * FRI" # At Fri midnight run this unit test.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo code
        uses: actions/checkout@v2 
        with:
          ref: "master"

      - name: build and run the restapi
        run: chmod +x ./kickstart_unit_test.sh && ./kickstart_unit_test.sh
